export const ADD_FEED_PROFILE_LIST_REQUEST =
  "addFeedProfile/ADD_FEED_PROFILE_LIST_REQUEST";
export const ADD_FEED_PROFILE_LIST_SUCCESS =
  "addFeedProfile/ADD_FEED_PROFILE_LIST_SUCCESS";
export const ADD_FEED_PROFILE_LIST_FAIL =
  "addFeedProfile/ADD_FEED_PROFILE_LIST_FAIL";

export const ADD_FEED_PROFILE_DETAILS_REQUEST =
  "addFeedProfile/ADD_FEED_PROFILE_DETAILS_REQUEST";
export const ADD_FEED_PROFILE_DETAILS_SUCCESS =
  "addFeedProfile/ADD_FEED_PROFILE_DETAILS_SUCCESS";
export const ADD_FEED_PROFILE_DETAILS_FAIL =
  "addFeedProfile/ADD_FEED_PROFILE_DETAILS_FAIL";

export const ADD_FEED_PROFILE_FOLLOW_REQUEST =
  "addFeedProfile/ADD_FEED_PROFILE_FOLLOW_REQUEST";
export const ADD_FEED_PROFILE_FOLLOW_SUCCESS =
  "addFeedProfile/ADD_FEED_PROFILE_FOLLOW_SUCCESS";
export const ADD_FEED_PROFILE_FOLLOW_FAIL =
  "addFeedProfile/ADD_FEED_PROFILE_FOLLOW_FAIL";
