# Generated by Django 4.1.1 on 2022-11-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case_division',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Case_Divisions'},
        ),
        migrations.AlterField(
            model_name='case',
            name='case_docs',
            field=models.FileField(blank=True, upload_to='client/images/case_file'),
        ),
    ]
