# Generated by Django 4.1.1 on 2022-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_case_division_options_alter_case_case_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='division',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
