# Generated by Django 4.1.1 on 2022-11-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_socity_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
