# Generated by Django 4.1.1 on 2022-11-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
