# Generated by Django 4.1.1 on 2022-11-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profileimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImages',
        ),
    ]
