# Generated by Django 4.1.1 on 2022-12-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyergroup',
            name='group_photo',
            field=models.ImageField(blank=True, default='client/default/sampleGroup.jpg', upload_to='client/images/group_pic/'),
        ),
    ]
