# Generated by Django 4.1.1 on 2022-11-08 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('group_desc', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Member',
            fields=[
                ('group_user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('join_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='group_images')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group_member')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Group_Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_opnion_post', to='group.group_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_opioner', to='group.group_member')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_group_post', to='group.group_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_liker', to='group.group_member')),
            ],
        ),
    ]
