# Generated by Django 4.1.1 on 2022-11-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_post',
            options={},
        ),
        migrations.AlterField(
            model_name='group_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='client/images/group_images'),
        ),
    ]
