# Generated by Django 4.1.1 on 2022-12-02 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('tags', models.CharField(choices=[('Articles', 'articles'), ('Books', 'books'), ('News', 'news'), ('Files', 'files')], default='Articles', max_length=50)),
                ('files', models.FileField(blank=True, upload_to='client/images/case_study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
