# Generated by Django 4.1.1 on 2022-12-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
