# Generated by Django 4.1.1 on 2022-12-03 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0002_casestudy_article_alter_casestudy_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casestudy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
