# Generated by Django 4.1.1 on 2022-12-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0003_casestudy_created_casestudy_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='images',
            field=models.ImageField(blank=True, upload_to='client/images/case_study/images'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='files',
            field=models.FileField(blank=True, upload_to='client/images/case_study/files'),
        ),
    ]
