# Generated by Django 4.1.1 on 2022-11-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpost', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
